### ISSUE TITLE
feature: switching game environment: web/desktop

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#1]
what i really miss is:
portability between environments: WEB/DESKTOP

we should "think small" first!
assume we only want to render shape as WIRE-FRAME

ruby code will have to implement some kind of simple model that will hold the vertex array.

EXAMPLE: for a model which defines a triangle and wants to be rendered as wire-frame.

<h4>

triangles fixnum=true renderAs="wireframe" 
   vertex  0,0,0
   vertex  0,0,1
   vertex  0,1,0
triangles

</h4>

this kind of vertex array will define a shape which will be able to be rendered by jax.view.render_webgl
jax.view.render_desktop
and most imprtant: without any change to the model!

afterwards: 
the controller implementation should also be portable between environments,
and maybe u should limit the syntax to be used in the controller so that porting between ruby and javascript will be more immidiate.

thanks ! :)

**Comment by sinisterchipmunk** [comment]
Because the code produced by Jax is entirely JavaScript, it would be feasible to use a Ruby wrapper around V8 (like [Tomato](http://github.com/sinisterchipmunk/tomato) ) to interpret it. Then, you just need to fill in the blanks by wrapping around a gem like [ruby-opengl](http://ruby-opengl.rubyforge.org/) with WebGL-compatible methods. (Something like this may even exist today, considering Chrome must have had to implement it.) It's not a trivial task but it is at least conceivable.

For now, my spare time will be spent entirely on Jax. While it would be awesome, this feature is both a significant undertaking and not really related to Jax itself. It'd be much better approached as a separate gem that bridges the various code bases already in existence, to avoid reinventing the wheel.
