### ISSUE TITLE
to be added: fps window 

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#10]
option  to report low fps by supplying a calculated average.

**Comment by sinisterchipmunk** [comment]
Jax now (as of v0.0.0.6) calculates framerate and update rate via the `Jax.Context#getFramesPerSecond()` and `Jax.Context#getUpdatesPerSecond()`. With this info it should be easy to implement a reporting system based on whatever algorithm you want -- but such a reporting system is currently outside the Jax scope, so it'll have to be implemented within the target application.

See `/spec/example_app/spec/javascripts/support/spec_layout.html.erb` for an example utilizing these methods; the same example is also auto-generated for new applications, but won't be available in old ones since they already have a spec layout.
