### ISSUE TITLE
How does one run the courthouse example?

### ISSUE THREAD

**Issue by raels** [sinisterchipmunk/jax#11]
It's in the example app, but I can't seem to get the route correct.  I tried adding routes for courthouse and courthouse/index but that didn't work.  Any advise appreciated.

Also, the tutorial says to go to localhost:8888 but jasmine is starting at port 8889.

**Comment by sinisterchipmunk** [comment]
I'm sorry, I should have clarified this somewhere.

The example app is in flux at the moment. Originally, the "example" app was an example for _me_ to follow -- the ideal Jax application that the framework should eventually generate/support. As the framework itself has progressed into a more usable state, the examples have become more solid and the app has become more of a real example (e.g. an example for _you_ instead of an example for _me_). However, some of that original, non-working code is still in place. The 'lighting' and 'texture' controllers are examples that do work properly. The 'courthouse' example is old, non-working code, part of the original guidelines I had set for myself. I'm set to remove the courthouse controller entirely over the next few days.

I've been working on another, more satisfying demo over the weekend, which really showcases some interesting effects. It actually turned out pretty nicely IMHO, and I'll likely turn a variant of it into a complete tutorial soon. If you wish, you can check out the source code here:

http://github.com/sinisterchipmunk/jax-dungeon

The new demo showcases point lighting, keyboard/mouse input handling, texturing, normal/bump mapping and procedural 3D model generation. The map data is actually just ASCII and the 'dungeon' model generates the 3D form of it on-the-fly.

I hope to add some collision detection, torch models on the walls (instead of just light sources emitting out of nothing), fire via particle generators, and other tweaks in the near future.

As for the example app starting on port 8889, this is because I hacked the port number into the example app so that it wouldn't conflict with Jax itself. That way I can develop Jax in parallel and then immediately switch over to testing the example app without worrying about restarting servers. Normally, apps will start on port 8888 as advertised.
