### ISSUE TITLE
bug reporting improvement: when running main jax testing suit i want to be able to report my local errors

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#3]
is it possible to auto-paste my errors to github.com/../jax/issues ?

**Comment by sinisterchipmunk** [comment]
I don't know, but I think that would be unwise because some errors could very likely be due to simple things like machine settings or missing dependencies. Also, it's possible I'll commit code that produces errors, in which case I already know about them. Until the first official release, the source code is going to be in a constant state of change and errors will be common. If you're certain an error is due to a real bug (and it's not coming from incomplete code), please just copy and paste it the hard way. Thanks!
