### ISSUE TITLE
jax+devinity: mvc to webgl/desktop ?

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#6]
may jax activity bring to life this award-winning project :
https://github.com/sinisterchipmunk/divinity

**Comment by sinisterchipmunk** [comment]
Divinity was a failed project. The problem was due mostly to the slowness of Ruby 1.8, and that I couldn't get it to work at all on Ruby 1.9.1. I haven't tried to work on it since Ruby 1.9.2 came out; maybe it would work, but I have no motivation to try. I think WebGL will make it fairly obsolete in the near(ish?) future. Anyone who wants to do so can try to revive it, however.
