### ISSUE TITLE
how jax will be integrated into a rails app ?

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#8]
throw some bones !

**Comment by sinisterchipmunk** [comment]
I haven't even begun to define how this will happen, because Jax itself is still being designed. There are, however, a few things that I can see happening:
- The Jax-Rails adapter will be a separate Ruby gem from Jax itself. This is because not all Jax users will want to use Rails, and working both Rails and non-Rails support into the gem would be dangerous (read: fragile).
- Jax will hook into the Rails #to_prepare step, so that the project can be rebuilt at every request without needing a Jasmine server to run.
- Jax will hook into the Rails rake tasks to invoke unit tests without needing any other special setup.
- Jax projects will (probably?) live in "app/jax", and Jax will take care of copying the necessary files into public/ as needed. This keeps resource files, etc. safe from prying eyes.
- There will, of course, be Ruby-side helpers. Ideally, there will be a JaxController that you can inherit from, moving a lot of code from Javascript into Ruby. I'm not sure how viable this will be at the moment, but I did some very similar things with my original webgl project ( http://github.com/sinisterchipmunk/webgl ).
- This isn't really a Rails thing, per se, but Jax will automatically convert known file types (MD2, MD3, BSP, etc) into JSON using Ruby. Since this is done server-side, it will add no JS client overhead (except to retrieve the corresponding JSON files).
  - One possible Rails-specific addition would be an engine controller to do the conversions on-the-fly and cache the JSON. This would keep the application directory cleaner than a "vanilla" Jax app would.
- Jax will almost certainly be able to use the Rails database to load resources, instead of storing them on the filesystem. It will likely support both file-based and DB-based resource management.

That's all I can think of right now. REMEMBER: this is really more of a wishlist right now. For the time being, I just want to release Jax v0.0.1, and I'll work on Rails adapters once Jax reaches, say, v0.1. Or someone else can start sooner than that, if they want.
