### ISSUE TITLE
mimic functionality of the project "gltail"

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#9]
how easy will it be to make rendering of  text info such as rails log files ?
i've yet to encounter a web application that do a nice visualization.

i want to create a self-explaining application, one that expose its own memory usage ..
something like a debugger interface that make u laugh :))

please show me the big money!

**Comment by sinisterchipmunk** [comment]
This isn't really a Jax issue, but....

To read the log file is as simple as @lines = File.open(...) { ... } in the controller, and rendering @lines in the view. Beware of exactly how you read it, though, because the log file can get quite large and Ruby will often attempt to read the whole thing at once. Check the Ruby docs for more info on File.

If you mean rendering the text via WebGL using Jax, then that's a little more on-topic...
- Jax will have full support for 2D and 3D text in its first (v0.0.1) release. I'll be adding that almost immediately after I finish adding support for bump maps (which are about 75% complete as of now). It will also feature support for video and other animated / rapidly-changing textures.
